apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app: {{ .Values.app.name }}
    helm.sh/chart: {{ include "cognito-webhook.chart" . }}
    app.kubernetes.io/name: {{ include "cognito-webhook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}