apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
    helm.sh/chart: {{ include "cognito-webhook.chart" . }}
    app.kubernetes.io/name: {{ include "cognito-webhook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.database.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-registry-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
    helm.sh/chart: {{ include "cognito-webhook.chart" . }}
    app.kubernetes.io/name: {{ include "cognito-webhook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.imageCredentials.registry .Values.imageCredentials.username .Values.imageCredentials.password (printf "%s:%s" .Values.imageCredentials.username .Values.imageCredentials.password | b64enc) | b64enc }}