# Values injected from GitHub Variables
app:
  name: cognito-webhook
  title: "Cognito K3s Webhook"
  description: "FastAPI microservice for handling Cognito PostConfirmation events"
  version: "1.0.0"
  port: 8000

image:
  registry: registry.cloud-it.com.ar
  name: cognito-k3s-webhook
  tag: latest
  pullPolicy: Always

imageCredentials:
  registry: registry.cloud-it.com.ar
  username: admin
  password: admin

deployment:
  replicas: 2
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

ingress:
  enabled: true
  host: webhook-rrhh.cloud-it.com.ar
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    enabled: true
    secretName: cognito-webhook-tls

database:
  host: postgresql-service.postgresql.svc.cluster.local
  port: 5432
  name: agent
  user: postgres
  password: 
  usersTable: users

cognito:
  triggerSource: PostConfirmation_ConfirmSignUp
  defaultProvider: google
  testUserPoolId: us-east-1_MeClCiUAC
  testRegion: us-east-1

namespace: rrhh-agent

logging:
  level: info
